### ISSUE TITLE
vrep robot model problem

### ISSUE THREAD

**Issue by woiazbl66** [LUHbots/luh_youbot_os#2]
I am trying to use the vrep model, but when I load the model, it is misplaced. Can you guys replace the current one with a new good one?
Thank you very much!

**Comment by woiazbl66** [comment]
Anyone help? I used another youbot model and another gripper, now I am driven crazy by the highly customized luh_youbot_kinematics package when trying to move the arm.

**Comment by siaden** [comment]
Our vrep model is actually deprecated. We switched to gazebo a few years ago and haven't used the vrep simulation since then. So we won't put any further effort into the vrep model. Sorry.
The main problem with vrep was that the simulation was very slow due to the LUA-Scripts. The C++-Plugins for Gazebo are much faster.
What exactly do you mean by 'misplaced'? Maybe I can help if you describe the problem in more detail.
In the kinematic lilbrary there is just one gripper-specific parameter, which is the length of the last arm segment (L4) in luh_youbot_kinematics/include/luh_youbot_kinematics/constants.h

**Comment by woiazbl66** [comment]
![screenshot from 2017-05-31 11-51-39](https://cloud.githubusercontent.com/assets/27451845/26641144/9cc92da0-45f7-11e7-81f5-0e3f119ef7fa.png)

When I say it is "misplaced", I mean the arm is not at the right place as shown in the pic I attached. I wonder if you have a correct model.

**Comment by woiazbl66** [comment]
Also, before I didn't compile the gazebo package, now I tried it, I get some error. Do I have to install the gazebo environment before compiling the gazebo package?
Thank you.
